spring:
  application:
    name: railway-reservation-system
  datasource:
    url: jdbc:mysql://localhost:3306/springbootlearning
    username: springbootuser
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

train:
  start: A
  end: E
  total-stations: 5
  count:
    max-passengers-for-single-booking: 8
    min-passengers-for-single-booking: 1
    waiting-upper-bound: 50
  seats:
    start: 1
    end: 8
  coach-name: UR